version: '3.8'

services:
  drupal:
    image: drupal:11-php8.3-fpm-alpine
    restart: unless-stopped
    environment:
      - DRUPAL_DATABASE_HOST=database
      - DRUPAL_DATABASE_PORT=3306
      - DRUPAL_DATABASE_NAME=${DB_NAME:-drupal}
      - DRUPAL_DATABASE_USERNAME=${DB_USER:-drupal}
      - DRUPAL_DATABASE_PASSWORD=${DB_PASSWORD:-drupal}
      - PHP_FPM_PM=dynamic
      - PHP_FPM_PM_MAX_CHILDREN=20
      - PHP_FPM_PM_START_SERVERS=2
      - PHP_FPM_PM_MIN_SPARE_SERVERS=1
      - PHP_FPM_PM_MAX_SPARE_SERVERS=3
    volumes:
      - drupal_files:/opt/drupal/web/sites/default/files
      - ./web:/opt/drupal/web
      - ./recipes:/opt/drupal/recipes
    depends_on:
      - database
      - redis

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8888:80"
    volumes:
      - ./web:/opt/drupal/web:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - drupal

  database:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_NAME:-drupal}
      - MYSQL_USER=${DB_USER:-drupal}
      - MYSQL_PASSWORD=${DB_PASSWORD:-drupal}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-drupal_root}
    volumes:
      - db_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
volumes:
  drupal_files:
  web:
  recipes:
  db_data:
  redis_data:
