version: '3.8'

services:
  drupal:
    image: drupal:11-apache
    restart: unless-stopped
    ports:
      - "80"
    environment:
      - DB_HOST=database
      - DB_NAME=${DB_NAME:-drupal}
      - DB_USER=${DB_USER:-drupal}
      - DB_PASSWORD=${DB_PASSWORD:-drupal}
      - APACHE_DOCUMENT_ROOT=/var/www/html/web
    volumes:
      - type: bind
        source: ../web
        target: /var/www/html/web
      - type: volume
        source: drupal_modules
        target: /var/www/html/web/modules
      - type: volume
        source: drupal_profiles
        target: /var/www/html/web/profiles
      - type: volume
        source: drupal_themes
        target: /var/www/html/web/themes
      - type: volume
        source: drupal_sites
        target: /var/www/html/web/sites
    depends_on:
      - database
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/web || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  database:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_NAME:-drupal}
      - MYSQL_USER=${DB_USER:-drupal}
      - MYSQL_PASSWORD=${DB_PASSWORD:-drupal}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-drupal_root}
    volumes:
      - db_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD:-drupal_root}"]
      interval: 5s
      timeout: 10s
      retries: 20

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "80"
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-drupal_root}
      - PMA_ARBITRARY=1
    depends_on:
      - database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:
  db_data:
