version: '3.8'

services:
  drupal:
    image: drupal:11-php8.3-fpm-alpine
    restart: unless-stopped
    environment:
      - DRUPAL_DATABASE_HOST=database
      - DRUPAL_DATABASE_PORT=3306
      - DRUPAL_DATABASE_NAME=${DB_NAME:-drupal}
      - DRUPAL_DATABASE_USERNAME=${DB_USER:-drupal}
      - DRUPAL_DATABASE_PASSWORD=${DB_PASSWORD:-drupal}
      - PHP_FPM_PM=dynamic
      - PHP_FPM_PM_MAX_CHILDREN=20
      - PHP_FPM_PM_START_SERVERS=2
      - PHP_FPM_PM_MIN_SPARE_SERVERS=1
      - PHP_FPM_PM_MAX_SPARE_SERVERS=3
      - COMPOSER_ALLOW_SUPERUSER=1
    volumes:
      - drupal_files:/opt/drupal/web/sites/default/files
      - ../:/opt/drupal
      - drupal_vendor:/opt/drupal/vendor
      - drupal_core:/opt/drupal/web/core
      - drupal_contrib_modules:/opt/drupal/web/modules/contrib
      - drupal_contrib_themes:/opt/drupal/web/themes/contrib
      - drupal_contrib_profiles:/opt/drupal/web/profiles/contrib
      - drupal_libraries:/opt/drupal/web/libraries
    entrypoint: |
      sh -c '
      if [ ! -d /opt/drupal/vendor ]; then
          echo "Running composer install..."
          cd /opt/drupal
          composer install --no-dev --optimize-autoloader
      fi
      php-fpm
      '
    depends_on:
      - database
      - redis

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80"
    volumes:
      - ../web:/opt/drupal/web:ro
      - type: bind
        source: ./nginx
        target: /etc/nginx/conf.d
        read_only: true
    depends_on:
      - drupal

  database:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_NAME:-drupal}
      - MYSQL_USER=${DB_USER:-drupal}
      - MYSQL_PASSWORD=${DB_PASSWORD:-drupal}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-drupal_root}
    volumes:
      - db_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "80"
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-drupal_root}
      - PMA_ARBITRARY=1
    depends_on:
      - database

volumes:
  drupal_files:
  drupal_vendor:
  drupal_core:
  drupal_contrib_modules:
  drupal_contrib_themes:
  drupal_contrib_profiles:
  drupal_libraries:
  db_data:
  redis_data:
